# Generated by Django 4.1.5 on 2023-06-16 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Details', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='family_members',
            field=models.IntegerField(blank=True, default=1),
        ),
    ]
