# Generated by Django 4.1.5 on 2023-06-21 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Details', '0003_profile_family_members'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='user_images/'),
        ),
    ]
