# Generated by Django 4.1.5 on 2023-06-22 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AI', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='health',
            name='age',
        ),
    ]
